### ISSUE TITLE
Uniting development power

### ISSUE THREAD

**Issue by connorlanigan** [Calrama/TextSecureFX#1]
Seeing your opened issue at [libtextsecure-java](/WhisperSystems/libtextsecure-java), I found your proof-of-concept client in Scala. I'm working on a desktop client as well (called [Norvos](/StarfishInteractive/norvos)), and as it is written in JavaFX, it is essentially targeting the same platform as TextSecureFX. 
Quite a lot of code has already been produced at Norvos, so I would love to focus our work together on one advanced code base. Would you be interested in joining the Norvos project?

**Comment by Calrama** [comment]
I have looked over the Norvos sources and I do recognize the advantage of pooling our manpower. However, I have a distinct dislike of both reading and writing Java code in my free time (since IMHO seemingly 90% of it is just boilerplate). As such simply moving over to the Java-based Norvos is sadly not an option for me. What we could, arguably, do is create a shared code base for the TextSecure communication stuff (Key generation, registration, sending, receiving, Axolotl store, etc.) with mixed Java/Scala code and use that in our respective clients. Or - though I suspect that is not of interest to you, since you have already invested a considerable amount of time in writing Java code - Norvos could be moved to a mixed Scala/Java code base with the goal of moving it later to Scala-only.

**Comment by connorlanigan** [comment]
Thanks for the suggestions. Unfortunately, moving Norvos to Scala would be a lot of work, especially as I have next to experience programming in Scala. Currently I neither have the time nor priority to learn Scala as a new language.
Sharing a mixed-language code base for communicatoin is a thing I'm interested in. I would recommend moving this discussion from the issue tracker to e-mail exchange (I'm reachable at the e-mail address listed on my Github profile). Please contact me.
